tap "homebrew/bundle"

brew 'awscli'
brew 'bat'
brew 'ctags'
brew 'fish'
brew 'fzf'
brew 'gh'
brew 'git-delta'
brew 'gpg'
brew 'helmfile'
brew 'kubectx'
brew 'k9s'
brew 'neovim'
brew 'node@22', link: true
brew 'pinentry-mac'
brew 'prettierd'
brew 'ripgrep'
brew 'stylua'
brew 'yt-dlp'

cask 'aws-vault'
cask 'browserstacklocal'
cask 'discord'
cask 'font-powerline-symbols'
cask 'font-victor-mono'
cask 'font-victor-mono-nerd-font'
cask 'ghostty'
cask 'google-chrome'
cask 'mullvadvpn'
cask 'orbstack'
cask 'session-manager-plugin'
cask 'shiori'
cask 'slack'
