set -x RUBYOPT -Ku

set -x NLS_LANG "AMERICAN_AMERICA.UTF8"
set -x ORACLE_HOME /opt/oracle/instantclient_10_2
set -x DYLD_LIBRARY_PATH $ORACLE_HOME
set -x LD_LIBRARY_PATH $ORACLE_HOME
set PATH $ORACLE_HOME $PATH
