#!/usr/bin/env bash

getDefaultSinkName() {
    pacmd stat | awk -F": " '/^Default sink name: /{print $2}'
}

getDefaultSinkVolume() {
    pacmd list-sinks |
        awk '/^\s+name: /{indefault = $2 == "<'$(getDefaultSinkName)'>"}
            /^\s+volume: / && indefault {print $5; exit}' |
        awk -F"%" '{print $1}'

}

isDefaultSinkMute() {
    pacmd list-sinks |
        awk '/^\s+name: /{indefault = $2 == "<'$(getDefaultSinkName)'>"}
            /^\s+muted: / && indefault {print $2; exit}' |
            grep 'yes'
}

interval=10
isMute=$(isDefaultSinkMute)
currentVolume=$(getDefaultSinkVolume)
minVolume=0
maxVolume=100

if [ "$1" == "UP" ]; then
  if [ $isMute ]; then
    pactl set-sink-mute @DEFAULT_SINK@ 0
  else
    volume=$(echo "$currentVolume + $interval" | bc)

    if (( $(echo "$maxVolume < $volume" | bc -l) == 0 ))
    then
      pactl set-sink-volume @DEFAULT_SINK@ +$interval%
    else
      pactl set-sink-volume @DEFAULT_SINK@ 100%
    fi
  fi
else
  volume=$(echo "$currentVolume - $interval" | bc)

  if (( $(echo "$minVolume >= $volume" | bc -l) == 0 ))
  then
    pactl set-sink-volume @DEFAULT_SINK@ -$interval%
  else
    pactl set-sink-mute @DEFAULT_SINK@ 1
    pactl set-sink-volume @DEFAULT_SINK@ 0%
  fi
fi
